[package]
name = "world-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-util.workspace = true
base64 = "0.22"
rand = "0.8"
subtle = "2"
fs2 = "0.4"
bytes = "1"
http-body-util = "0.1"
hyper = { version = "1", features = ["http1", "server", "client"] }
hyper-util = { version = "0.1", features = ["tokio"] }
world-tmp-path = { path = "../world-tmp-path" }
