//! Differential test: apply the same random operation sequences to a
//! [`world_fsmodel::Model`] (a plain subtree, no temp-root mounts, see
//! `Model::new_plain`) and to a real, empty scratch directory, and check
//! that the model's `ret`/`errno`/`data` agree with what the real kernel
//! did. This is what validates the oracle itself, independent of anything
//! World-specific: it runs natively (no shim) on macOS locally and on Linux
//! in CI.
//!
//! ## Sandboxing
//!
//! This test performs real, mutating filesystem syscalls (`mkdir`, `open`,
//! `rename`, `unlink`, ...) driven by randomly generated operation
//! sequences. To make it safe to run unattended even if a future generator
//! change (or a bug in this harness) ever produced an escaping path, every
//! operand is:
//!
//! 1. Executed via `*at` syscalls (`openat`/`mkdirat`/`unlinkat`/
//!    `renameat`/`symlinkat`/`readlinkat`/`fstatat`) against a `dirfd`
//!    opened once on the canonical scratch directory -- this process never
//!    calls `chdir`/`set_current_dir`, so there is no ambient cwd state for
//!    a relative path to exploit.
//! 2. Checked by [`guard`] before the syscall runs: the operand must be a
//!    bare, single-component name (no `/`, no `.`/`..`), and the `dirfd`'s
//!    own canonical path (re-resolved every time via `F_GETPATH`/
//!    `/proc/self/fd`) must still be nested under the canonical scratch
//!    root. A rejected operand is *never* executed; it is recorded as a
//!    harness error and both sides of that one op are skipped. See
//!    `guard_rejects_escaping_rename` for a direct demonstration.
//! 3. On macOS, the whole test process re-execs itself under
//!    `sandbox-exec` (see `ensure_sandboxed_or_reexec`) with a profile that
//!    denies `file-write*` everywhere except the scratch tree, macOS's own
//!    `/private/var/folders` (where TMPDIR-relative test-harness output can
//!    land) and `/dev` (ttys/null); this is a second, OS-enforced layer
//!    below the in-process guard. If `sandbox-exec` is unavailable, the test
//!    is skipped (with a message) rather than run unsandboxed. On Linux,
//!    guards 1-2 are the safety net.
//! 4. Cleaned up only via `remove_dir_all` on the exact canonical scratch
//!    path, and only after asserting that path contains the expected
//!    `fsmodel-conformance` marker component (see `cleanup`).
//!
//! The op mix is deliberately restricted to what `libc` can do portably
//! without a process-wide `chdir`: `Mkdir`, `Open` (create/excl/trunc/write
//! combinations), `Write`, `Read`, `Symlink`, `Readlink`, `Rename`,
//! `Unlink`, `Rmdir`, `Stat`, `Lstat`, `List`, `CloseFd`. Every operand is a
//! bare name with no path separators, so nothing generated by [`gen_ops`]
//! can address anything outside the scratch directory in the first place;
//! the guard is defense in depth, not the only thing standing between the
//! generator and the real filesystem.
use std::collections::HashMap;
use std::ffi::CString;
use std::fs::File;
use std::io;
use std::os::fd::{AsRawFd, FromRawFd, OwnedFd, RawFd};
use std::os::unix::ffi::OsStrExt;
use std::path::{Path, PathBuf};

use world_fsmodel::{Model, Op, OpenFlags, Outcome, errno_equiv};

/// Set on the re-exec'd (or non-macOS) process so it does not re-wrap
/// itself again.
const SANDBOX_MARKER: &str = "WORLD_FSMODEL_SANDBOXED";

/// Number of random op sequences to run; each sequence starts from a fresh
/// empty directory. Override with `WORLD_FSMODEL_CASES`.
fn case_count() -> usize {
    std::env::var("WORLD_FSMODEL_CASES")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(50)
}

/// Ops per sequence.
const OPS_PER_CASE: usize = 40;

/// A small splitmix64-derived PRNG so this test needs no dependency beyond
/// std/libc.
struct Rng(u64);
impl Rng {
    fn new(seed: u64) -> Rng {
        Rng(seed)
    }
    fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }
    fn below(&mut self, n: usize) -> usize {
        if n == 0 {
            0
        } else {
            (self.next_u64() % n as u64) as usize
        }
    }
    fn chance(&mut self, pct: u64) -> bool {
        self.next_u64() % 100 < pct
    }
}

/// A conformance-test-local operation. `id` fields are synthetic ids shared
/// verbatim by both the model side (via a synthetic-id -> model-fd map) and
/// the real side (as a direct key into its own open-file table), so a
/// sequence can be generated once and replayed identically on both. Every
/// `String` operand here is a bare name (see [`gen_name`]): the generator
/// never emits `/`, `.` or `..`, so nothing here can name anything outside
/// the directory the harness opens its `dirfd` on.
#[derive(Debug, Clone)]
enum COp {
    Mkdir(String),
    Create {
        path: String,
        excl: bool,
        trunc: bool,
        id: u32,
    },
    Write {
        id: u32,
        data: Vec<u8>,
    },
    Read {
        id: u32,
        len: usize,
    },
    Symlink {
        target: String,
        path: String,
    },
    Readlink(String),
    Rename {
        from: String,
        to: String,
    },
    Unlink(String),
    Rmdir(String),
    Stat(String),
    Lstat(String),
    List(String),
    Close(u32),
}

fn gen_name(rng: &mut Rng, existing: &[String]) -> String {
    // Bias towards names that already exist, so ops actually interact.
    if !existing.is_empty() && rng.chance(60) {
        existing[rng.below(existing.len())].clone()
    } else {
        let letters = b"abc";
        let len = 1 + rng.below(3);
        (0..len)
            .map(|_| letters[rng.below(letters.len())] as char)
            .collect()
    }
}

fn gen_ops(rng: &mut Rng, n: usize) -> Vec<COp> {
    let mut names: Vec<String> = Vec::new();
    let mut open_ids: Vec<u32> = Vec::new();
    let mut next_id = 0u32;
    let mut ops = Vec::new();
    for _ in 0..n {
        let op = match rng.below(12) {
            0 => {
                let name = gen_name(rng, &names);
                names.push(name.clone());
                COp::Mkdir(name)
            }
            1 => {
                let path = gen_name(rng, &names);
                names.push(path.clone());
                let id = next_id;
                next_id += 1;
                open_ids.push(id);
                COp::Create {
                    path,
                    excl: rng.chance(30),
                    trunc: rng.chance(30),
                    id,
                }
            }
            2 if !open_ids.is_empty() => {
                let id = open_ids[rng.below(open_ids.len())];
                let len = rng.below(9);
                let data: Vec<u8> = (0..len).map(|i| b'A' + (i as u8 % 26)).collect();
                COp::Write { id, data }
            }
            3 if !open_ids.is_empty() => {
                let id = open_ids[rng.below(open_ids.len())];
                COp::Read {
                    id,
                    len: rng.below(20),
                }
            }
            4 => {
                let target = gen_name(rng, &names);
                let path = gen_name(rng, &names);
                names.push(path.clone());
                COp::Symlink { target, path }
            }
            5 => COp::Readlink(gen_name(rng, &names)),
            6 => COp::Rename {
                from: gen_name(rng, &names),
                to: gen_name(rng, &names),
            },
            7 => COp::Unlink(gen_name(rng, &names)),
            8 => COp::Rmdir(gen_name(rng, &names)),
            9 => COp::Stat(gen_name(rng, &names)),
            10 => COp::Lstat(gen_name(rng, &names)),
            _ => COp::List(gen_name(rng, &names)),
        };
        ops.push(op);
        if rng.chance(15) && !open_ids.is_empty() {
            let idx = rng.below(open_ids.len());
            ops.push(COp::Close(open_ids.remove(idx)));
        }
    }
    ops
}

// ---------------------------------------------------------------------
// Sandbox guard: every real operand passes through here before it ever
// reaches a syscall. See the module docs and `guard_rejects_escaping_rename`
// below for the point of this.
// ---------------------------------------------------------------------

/// The dirfd's own canonical path, re-resolved fresh every call (never
/// cached): `F_GETPATH` on macOS, `/proc/self/fd/<n>` on Linux.
fn dirfd_realpath(dirfd: RawFd) -> io::Result<PathBuf> {
    #[cfg(target_os = "macos")]
    {
        let mut buf = vec![0u8; libc::PATH_MAX as usize];
        let ret = unsafe { libc::fcntl(dirfd, libc::F_GETPATH, buf.as_mut_ptr()) };
        if ret != 0 {
            return Err(io::Error::last_os_error());
        }
        let len = buf.iter().position(|&b| b == 0).unwrap_or(buf.len());
        Ok(PathBuf::from(std::ffi::OsStr::from_bytes(&buf[..len])))
    }
    #[cfg(not(target_os = "macos"))]
    {
        std::fs::read_link(format!("/proc/self/fd/{dirfd}"))
    }
}

/// Guard (b)/(c) from the task: refuse to run a real syscall for `name`
/// unless (1) it is a bare, single, non-dot(dot) path component -- so it can
/// never itself contain a `..` or absolute jump -- and (2) `dirfd`'s own
/// canonical path is still nested under `scratch` right now. Returns the
/// dirfd's resolved path on success (callers that already need it can reuse
/// it instead of resolving twice).
fn guard(scratch: &Path, dirfd: RawFd, name: &str) -> Result<PathBuf, String> {
    if name.is_empty() || name == "." || name == ".." || name.contains('/') {
        return Err(format!("refusing non-bare operand {name:?}"));
    }
    let dir_path = dirfd_realpath(dirfd)
        .map_err(|e| format!("could not resolve dirfd's own canonical path: {e}"))?;
    if !dir_path.starts_with(scratch) {
        return Err(format!(
            "dirfd canonical path {} is not nested under scratch root {}",
            dir_path.display(),
            scratch.display()
        ));
    }
    Ok(dir_path)
}

// ---------------------------------------------------------------------
// Raw `*at` syscall wrappers (portable macOS/Linux, no process-wide cwd).
// ---------------------------------------------------------------------

fn cstr(name: &str) -> CString {
    CString::new(name).expect("harness names never contain NUL")
}

fn openat_raw(dirfd: RawFd, name: &str, flags: i32, mode: u32) -> io::Result<RawFd> {
    let c = cstr(name);
    let fd = unsafe { libc::openat(dirfd, c.as_ptr(), flags, mode as libc::c_uint) };
    if fd < 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(fd)
    }
}

fn mkdirat_raw(dirfd: RawFd, name: &str, mode: u32) -> io::Result<()> {
    let c = cstr(name);
    let ret = unsafe { libc::mkdirat(dirfd, c.as_ptr(), mode as libc::mode_t) };
    if ret != 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(())
    }
}

fn unlinkat_raw(dirfd: RawFd, name: &str, flags: i32) -> io::Result<()> {
    let c = cstr(name);
    let ret = unsafe { libc::unlinkat(dirfd, c.as_ptr(), flags) };
    if ret != 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(())
    }
}

fn renameat_raw(from_fd: RawFd, from: &str, to_fd: RawFd, to: &str) -> io::Result<()> {
    let cf = cstr(from);
    let ct = cstr(to);
    let ret = unsafe { libc::renameat(from_fd, cf.as_ptr(), to_fd, ct.as_ptr()) };
    if ret != 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(())
    }
}

fn symlinkat_raw(target: &str, dirfd: RawFd, name: &str) -> io::Result<()> {
    let ct = cstr(target);
    let cn = cstr(name);
    let ret = unsafe { libc::symlinkat(ct.as_ptr(), dirfd, cn.as_ptr()) };
    if ret != 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(())
    }
}

fn readlinkat_raw(dirfd: RawFd, name: &str) -> io::Result<Vec<u8>> {
    let c = cstr(name);
    let mut buf = vec![0u8; 4096];
    let n = unsafe {
        libc::readlinkat(
            dirfd,
            c.as_ptr(),
            buf.as_mut_ptr().cast::<libc::c_char>(),
            buf.len(),
        )
    };
    if n < 0 {
        return Err(io::Error::last_os_error());
    }
    buf.truncate(n as usize);
    Ok(buf)
}

fn fstatat_raw(dirfd: RawFd, name: &str, flags: i32) -> io::Result<libc::stat> {
    let c = cstr(name);
    let mut st: libc::stat = unsafe { std::mem::zeroed() };
    let ret = unsafe { libc::fstatat(dirfd, c.as_ptr(), &mut st, flags) };
    if ret != 0 {
        Err(io::Error::last_os_error())
    } else {
        Ok(st)
    }
}

fn kind_code_from_mode(mode: libc::mode_t) -> u8 {
    match mode & libc::S_IFMT {
        libc::S_IFDIR => 0,
        libc::S_IFLNK => 2,
        _ => 1,
    }
}

fn list_at_raw(dirfd: RawFd, name: &str) -> io::Result<Vec<String>> {
    let sub_fd = openat_raw(
        dirfd,
        name,
        libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC,
        0,
    )?;
    // SAFETY: `sub_fd` is freshly opened and not otherwise used; fdopendir
    // takes ownership of it (closedir below closes it).
    let dirp = unsafe { libc::fdopendir(sub_fd) };
    if dirp.is_null() {
        let err = io::Error::last_os_error();
        unsafe { libc::close(sub_fd) };
        return Err(err);
    }
    let mut names = Vec::new();
    loop {
        // SAFETY: `dirp` is a live DIR* from fdopendir above.
        let entry = unsafe { libc::readdir(dirp) };
        if entry.is_null() {
            break;
        }
        // SAFETY: `d_name` is a NUL-terminated field of a valid dirent.
        let name = unsafe { std::ffi::CStr::from_ptr((*entry).d_name.as_ptr()) }
            .to_string_lossy()
            .into_owned();
        if name != "." && name != ".." {
            names.push(name);
        }
    }
    // SAFETY: `dirp` was opened above and not yet closed.
    unsafe { libc::closedir(dirp) };
    Ok(names)
}

fn ok(ret: i64) -> Outcome {
    Outcome {
        ret,
        errno: 0,
        data: Vec::new(),
    }
}
fn err(e: i32) -> Outcome {
    Outcome {
        ret: -1,
        errno: e,
        data: Vec::new(),
    }
}
fn real_errno(e: &io::Error) -> i32 {
    e.raw_os_error().unwrap_or(libc::EIO)
}

// ---------------------------------------------------------------------
// Real-side execution, guarded.
// ---------------------------------------------------------------------

/// Run one `COp` against the real filesystem via `dirfd` (opened on
/// `scratch`). Every name operand is checked by [`guard`] first; a rejected
/// operand short-circuits to `Ok(None)` ("harness skip": neither side runs
/// this op) rather than ever reaching a syscall.
fn run_real(
    scratch: &Path,
    dirfd: RawFd,
    op: &COp,
    files: &mut HashMap<u32, File>,
) -> Option<Outcome> {
    let g = |name: &str| guard(scratch, dirfd, name);
    let outcome = match op {
        COp::Mkdir(name) => {
            g(name).ok()?;
            match mkdirat_raw(dirfd, name, 0o755) {
                Ok(()) => ok(0),
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Create {
            path,
            excl,
            trunc,
            id,
        } => {
            g(path).ok()?;
            let mut flags = libc::O_RDWR | libc::O_CLOEXEC;
            flags |= if *excl {
                libc::O_CREAT | libc::O_EXCL
            } else {
                libc::O_CREAT
            };
            if *trunc {
                flags |= libc::O_TRUNC;
            }
            match openat_raw(dirfd, path, flags, 0o644) {
                Ok(fd) => {
                    // SAFETY: `fd` was just opened by us and not otherwise used.
                    files.insert(*id, unsafe { File::from_raw_fd(fd) });
                    ok(0)
                }
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Write { id, data } => match files.get_mut(id) {
            Some(f) => {
                use std::io::Write;
                match f.write(data) {
                    Ok(n) => ok(n as i64),
                    Err(e) => err(real_errno(&e)),
                }
            }
            None => err(libc::EBADF),
        },
        COp::Read { id, len } => match files.get_mut(id) {
            Some(f) => {
                use std::io::Read;
                let mut buf = vec![0u8; *len];
                match f.read(&mut buf) {
                    Ok(n) => Outcome {
                        ret: n as i64,
                        errno: 0,
                        data: buf[..n].to_vec(),
                    },
                    Err(e) => err(real_errno(&e)),
                }
            }
            None => err(libc::EBADF),
        },
        COp::Symlink { target, path } => {
            g(path).ok()?;
            // `target` is stored verbatim (never dereferenced by this
            // harness), so it does not need the bare-name guard: a dangling
            // or "weird" target is exactly the point of testing symlinks.
            match symlinkat_raw(target, dirfd, path) {
                Ok(()) => ok(0),
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Readlink(name) => {
            g(name).ok()?;
            match readlinkat_raw(dirfd, name) {
                Ok(bytes) => Outcome {
                    ret: bytes.len() as i64,
                    errno: 0,
                    data: bytes,
                },
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Rename { from, to } => {
            g(from).ok()?;
            g(to).ok()?;
            match renameat_raw(dirfd, from, dirfd, to) {
                Ok(()) => ok(0),
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Unlink(name) => {
            g(name).ok()?;
            match unlinkat_raw(dirfd, name, 0) {
                Ok(()) => ok(0),
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Rmdir(name) => {
            g(name).ok()?;
            match unlinkat_raw(dirfd, name, libc::AT_REMOVEDIR) {
                Ok(()) => ok(0),
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Stat(name) => {
            g(name).ok()?;
            match fstatat_raw(dirfd, name, 0) {
                Ok(st) => Outcome {
                    ret: 0,
                    errno: 0,
                    data: vec![kind_code_from_mode(st.st_mode)],
                },
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Lstat(name) => {
            g(name).ok()?;
            match fstatat_raw(dirfd, name, libc::AT_SYMLINK_NOFOLLOW) {
                Ok(st) => Outcome {
                    ret: 0,
                    errno: 0,
                    data: vec![kind_code_from_mode(st.st_mode)],
                },
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::List(name) => {
            g(name).ok()?;
            match list_at_raw(dirfd, name) {
                Ok(mut names) => {
                    names.sort();
                    let data = names.join("\n").into_bytes();
                    Outcome {
                        ret: names.len() as i64,
                        errno: 0,
                        data,
                    }
                }
                Err(e) => err(real_errno(&e)),
            }
        }
        COp::Close(id) => {
            if files.remove(id).is_some() {
                ok(0)
            } else {
                err(libc::EBADF)
            }
        }
    };
    Some(outcome)
}

/// Translate a `COp` into the frozen `Op` the model understands, using
/// `id_to_model_fd` to turn a synthetic id into the model's own
/// `apply`-assigned fd (for `Write`/`Read`/`Close`; other variants carry no
/// fd at all).
fn to_model_op(op: &COp, id_to_model_fd: &HashMap<u32, u32>) -> Op {
    let mfd = |id: &u32| *id_to_model_fd.get(id).unwrap_or(&u32::MAX);
    match op {
        COp::Mkdir(name) => Op::Mkdir {
            path: name.clone().into_bytes(),
            mode: 0o755,
        },
        COp::Create {
            path, excl, trunc, ..
        } => Op::Open {
            path: path.clone().into_bytes(),
            flags: OpenFlags {
                create: true,
                excl: *excl,
                trunc: *trunc,
                write: true,
                ..Default::default()
            },
        },
        COp::Write { id, data } => Op::Write {
            fd: mfd(id),
            data: data.clone(),
        },
        COp::Read { id, len } => Op::Read {
            fd: mfd(id),
            len: *len,
        },
        COp::Symlink { target, path } => Op::Symlink {
            target: target.clone().into_bytes(),
            path: path.clone().into_bytes(),
        },
        COp::Readlink(name) => Op::Readlink {
            path: name.clone().into_bytes(),
        },
        COp::Rename { from, to } => Op::Rename {
            from: from.clone().into_bytes(),
            to: to.clone().into_bytes(),
        },
        COp::Unlink(name) => Op::Unlink {
            path: name.clone().into_bytes(),
        },
        COp::Rmdir(name) => Op::Rmdir {
            path: name.clone().into_bytes(),
        },
        COp::Stat(name) => Op::Stat {
            path: name.clone().into_bytes(),
        },
        COp::Lstat(name) => Op::Lstat {
            path: name.clone().into_bytes(),
        },
        COp::List(name) => Op::List {
            path: name.clone().into_bytes(),
        },
        COp::Close(id) => Op::CloseFd { fd: mfd(id) },
    }
}

// ---------------------------------------------------------------------
// Scratch directory management.
// ---------------------------------------------------------------------

fn base_dir() -> PathBuf {
    std::env::var_os("CARGO_TARGET_TMPDIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../target/fsmodel-conformance")
        })
}

/// Create (or recreate) `base_dir()/case-<tag>-<pid>` and return its
/// *canonical* path.
fn make_scratch_dir(tag: &str) -> PathBuf {
    let base = base_dir();
    std::fs::create_dir_all(&base).expect("create conformance base dir");
    let pid = std::process::id();
    let dir = base.join(format!("case-{tag}-{pid}"));
    if dir.exists() {
        std::fs::remove_dir_all(&dir).ok();
    }
    std::fs::create_dir_all(&dir).expect("create case scratch dir");
    std::fs::canonicalize(&dir).expect("canonicalize scratch dir")
}

/// Cleanup guard (item 4): only ever `remove_dir_all` a path that is
/// unmistakably one of ours.
fn cleanup(scratch: &Path) {
    let text = scratch.to_string_lossy();
    assert!(
        text.contains("fsmodel-conformance") && text.contains("case-"),
        "refusing to remove_dir_all a path outside the expected scratch tree: {text}"
    );
    let _ = std::fs::remove_dir_all(scratch);
}

// ---------------------------------------------------------------------
// macOS sandbox-exec wrapper.
// ---------------------------------------------------------------------

/// If not already running inside the sandbox (`SANDBOX_MARKER` unset) and on
/// macOS, re-exec this same test binary (with the same arguments) under
/// `sandbox-exec`, wait for it, and exit with its status -- so the *outer*
/// `cargo test` invocation never itself touches the filesystem beyond
/// spawning that child. Returns `Err` (meaning "skip the test, do not run
/// unsandboxed") when `sandbox-exec` is unavailable. On non-macOS, returns
/// `Ok(())` immediately: guards in `run_real`/`guard` are the safety net
/// there.
fn ensure_sandboxed_or_reexec(test_name: &str) -> Result<(), String> {
    // Only used on macOS, to filter the re-exec'd child down to this one
    // test; unused (but still accepted, for a uniform call site) elsewhere.
    let _ = test_name;
    if std::env::var_os(SANDBOX_MARKER).is_some() {
        return Ok(());
    }
    if cfg!(not(target_os = "macos")) {
        return Ok(());
    }
    #[cfg(target_os = "macos")]
    {
        let sandbox_exec = Path::new("/usr/bin/sandbox-exec");
        if !sandbox_exec.exists() {
            return Err("sandbox-exec not found at /usr/bin/sandbox-exec".to_string());
        }
        let base = base_dir();
        std::fs::create_dir_all(&base).map_err(|e| format!("create base dir: {e}"))?;
        let canonical_base =
            std::fs::canonicalize(&base).map_err(|e| format!("canonicalize base dir: {e}"))?;
        let profile = format!(
            "(version 1)(allow default)(deny file-write* (require-not (require-any (subpath \"{}\") (subpath \"/private/var/folders\") (subpath \"/dev\"))))",
            canonical_base.display()
        );
        let exe = std::env::current_exe().map_err(|e| format!("current_exe: {e}"))?;
        // Re-run only this one test in the child: the outer (unsandboxed)
        // process's own test threads for everything else keep running
        // normally, and the child's `--exact` selection means it does not
        // redundantly repeat the other tests in this file.
        let status = std::process::Command::new(sandbox_exec)
            .arg("-p")
            .arg(&profile)
            .arg(&exe)
            .arg(test_name)
            .arg("--exact")
            .env(SANDBOX_MARKER, "1")
            .status()
            .map_err(|e| format!("spawn sandbox-exec: {e}"))?;
        std::process::exit(status.code().unwrap_or(1));
    }
    #[cfg(not(target_os = "macos"))]
    {
        unreachable!()
    }
}

// ---------------------------------------------------------------------
// Case runner.
// ---------------------------------------------------------------------

/// Apply one sequence of `COp`s to both the model and a real scratch
/// directory, asserting agreement after every op (so a divergence is
/// reported against the exact minimal op that caused it, not just the whole
/// sequence).
fn run_case(seed: u64) {
    let ops = gen_ops(&mut Rng::new(seed), OPS_PER_CASE);
    let scratch = make_scratch_dir(&seed.to_string());
    let anchor = scratch.as_os_str().as_bytes().to_vec();
    let mut model = Model::new_plain(&anchor);
    let mut real_files: HashMap<u32, File> = HashMap::new();
    let mut id_to_model_fd: HashMap<u32, u32> = HashMap::new();
    let mut harness_errors: Vec<String> = Vec::new();

    // SAFETY: opening a directory we just created/canonicalized ourselves.
    let dirfd = {
        let c = CString::new(scratch.as_os_str().as_bytes()).expect("scratch path has no NUL");
        let fd = unsafe {
            libc::open(
                c.as_ptr(),
                libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC,
            )
        };
        assert!(
            fd >= 0,
            "open scratch dirfd: {}",
            io::Error::last_os_error()
        );
        unsafe { OwnedFd::from_raw_fd(fd) }
    };

    for (i, cop) in ops.iter().enumerate() {
        let Some(real_out) = run_real(&scratch, dirfd.as_raw_fd(), cop, &mut real_files) else {
            harness_errors.push(format!("op {i} {cop:?}: guard rejected operand; skipped"));
            continue;
        };
        let model_out = model.apply(&to_model_op(cop, &id_to_model_fd));

        if let (COp::Create { id, .. }, 0) = (cop, model_out.errno) {
            id_to_model_fd.insert(*id, model_out.ret as u32);
        }

        let linux = cfg!(target_os = "linux");
        assert!(
            errno_equiv(linux, model_out.errno, real_out.errno),
            "case {seed} op {i} {cop:?}: errno mismatch model={} real={}",
            model_out.errno,
            real_out.errno
        );
        if model_out.errno == 0 {
            assert_eq!(
                model_out.ret >= 0,
                real_out.ret >= 0,
                "case {seed} op {i} {cop:?}: ret sign mismatch model={} real={}",
                model_out.ret,
                real_out.ret
            );
            match cop {
                COp::Read { .. } | COp::Readlink(_) | COp::List(_) => {
                    assert_eq!(
                        model_out.data, real_out.data,
                        "case {seed} op {i} {cop:?}: data mismatch"
                    );
                }
                COp::Stat(_) | COp::Lstat(_) => {
                    assert_eq!(
                        model_out.data.first(),
                        real_out.data.first(),
                        "case {seed} op {i} {cop:?}: stat kind mismatch"
                    );
                }
                _ => {}
            }
        }
    }
    assert!(
        harness_errors.is_empty(),
        "case {seed}: harness rejected operands: {harness_errors:?}"
    );
    drop(dirfd);
    cleanup(&scratch);
}

#[test]
fn model_agrees_with_the_real_kernel_on_random_op_sequences() {
    if let Err(msg) =
        ensure_sandboxed_or_reexec("model_agrees_with_the_real_kernel_on_random_op_sequences")
    {
        eprintln!(
            "SKIPPING model_agrees_with_the_real_kernel_on_random_op_sequences: {msg} \
             (refusing to run real, mutating filesystem ops unsandboxed)"
        );
        return;
    }
    for case in 0..case_count() {
        run_case(0xC0FF_EE00 + case as u64);
    }
}

/// Demonstrates that the sandbox guard actually rejects an escaping operand
/// rather than ever executing it: a `Rename` whose `to` climbs out of the
/// scratch directory must be refused by [`guard`] (via [`run_real`]
/// returning `None`), and the escaping path must never be created.
#[test]
fn guard_rejects_escaping_rename() {
    let scratch = make_scratch_dir("guard-demo");
    let dirfd = {
        let c = CString::new(scratch.as_os_str().as_bytes()).unwrap();
        let fd = unsafe {
            libc::open(
                c.as_ptr(),
                libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC,
            )
        };
        assert!(fd >= 0);
        unsafe { OwnedFd::from_raw_fd(fd) }
    };

    // A real file to (attempt to) rename.
    mkdirat_raw(dirfd.as_raw_fd(), "src", 0o755).unwrap();

    let mut files = HashMap::new();
    let escaping = COp::Rename {
        from: "src".to_string(),
        to: "../../escape".to_string(),
    };
    let result = run_real(&scratch, dirfd.as_raw_fd(), &escaping, &mut files);
    assert!(
        result.is_none(),
        "guard should have rejected the escaping rename, got {result:?}"
    );

    // The escaping target must not exist anywhere near the scratch parent.
    if let Some(parent) = scratch.parent().and_then(|p| p.parent()) {
        assert!(
            !parent.join("escape").exists(),
            "escaping rename target was actually created!"
        );
    }
    // And the original file must be untouched (rename never ran).
    assert!(
        fstatat_raw(dirfd.as_raw_fd(), "src", 0).is_ok(),
        "source should be untouched"
    );

    drop(dirfd);
    cleanup(&scratch);
}

/// The guard must also reject a plain `..`/`.`/empty operand and an operand
/// containing an embedded `/`, independent of any real filesystem state.
#[test]
fn guard_rejects_dotdot_dot_and_embedded_slash() {
    let scratch = make_scratch_dir("guard-demo2");
    let dirfd = {
        let c = CString::new(scratch.as_os_str().as_bytes()).unwrap();
        let fd = unsafe {
            libc::open(
                c.as_ptr(),
                libc::O_RDONLY | libc::O_DIRECTORY | libc::O_CLOEXEC,
            )
        };
        assert!(fd >= 0);
        unsafe { OwnedFd::from_raw_fd(fd) }
    };
    for bad in ["..", ".", "", "a/b", "../escape"] {
        assert!(
            guard(&scratch, dirfd.as_raw_fd(), bad).is_err(),
            "guard should reject operand {bad:?}"
        );
    }
    drop(dirfd);
    cleanup(&scratch);
}
