[package]
name = "world-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "world"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
libc.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
world-runtime = { path = "../world-runtime" }
clap = { version = "4", features = ["derive"] }
humantime = "2"

[dev-dependencies]
tempfile.workspace = true
libc.workspace = true
